### ISSUE TITLE
Generate list of available locales

### ISSUE THREAD

**Issue by Akryum** [caugner/vue-cli-locales#2]
@caugner Would it be possible to generate a JSON file with an array of all available locales in the root directory when we pull the locales from transifex?

**Comment by Akryum** [comment]
Found a way!

https://unpkg.com/vue-cli-locales@3.0.5/locales/?meta

**Comment by iampaulnorman1010** [comment]
> @caugner Would it be possible to generate a JSON file with an array of all available locales in the root directory when we pull the locales from transifex?

> @vue-cli-locales-bot
